# Generated by Django 5.2.7 on 2025-11-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookig_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
