# Generated by Django 5.2.7 on 2025-10-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_flight_booking_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
