# Generated by Django 5.2.7 on 2025-10-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_flight_booking_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
